---
title: DC Statuary
url: https://dc-statuary.com
timezone: America/New_York
collections:
  posts:
    title: posts
    output: true
  uploads:
    title: Uploads
    output: true
gems:
- jekyll-paginate
paginate: 3
paginate_path: "/page:num/"
hilighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
excerpt_separator: "<!-- more -->"
email: your-email@domain.com
exclude:
- ".gitignore"
- .gulpfile.js
- .package.json
description: |
  A growing collection of some of the great statuary hidden around the Nation’s capital. Forget about the big stuff—The Lincoln Memorial, The Washington Monument, etc.—D.C. is filled with small monuments and statues all across the district, let's celebrate as much of it as we can.
baseurl:
permalink: /:title
destination: "./build"
sass:
  style: compressed
